apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.name" .}}
  namespace: {{ template "common.namespaces" }}
  annotations:
    konghq.com/strip-path: 'true'
spec:
  ingressClassName: kong
  rules:
  - http: 'kong.example'
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ include "chart.name" .}}
            port:
              number: {{ .Values.deployment.containerPort }}