apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.name" .}}
  namespace: {{ template "common.namespaces" }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.deployment.containerPort }}
    protocol: TCP
    targetPort: {{ .Values.deployment.containerPort }}