apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ template "common.namespaces" }}
spec:
  selector: {{ include "common.labels" . | indent 4 }}
  ports:
  - port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.port }}