name: Release Charts
on:
  push:
    branches:
      - develop
jobs:
  update-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Git config
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Config Helm
        uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Upload chart version
        env:
          GIT_TOKEN: "${{ secrets.K8S_HELM_CHART_TOKEN }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          REPO_NAME: "${{ github.event.repository.name }}"
          OWNER_REPO: "namnextx"
          CHART_PACKAGE_PATH: .cr-release-packages
          CHART_REGISTRY: ghcr.io
        run: |
          chmod +x ./push_chart.sh
          sh ./push_chart.sh ${CHART_PACKAGE_PATH}