name: Release Charts
on:
  push:
    branches:
      - develop
jobs:
  update-chart:
    run-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: fetch-depth: 0

      - name: Initial Helm
        uses: azure/setup-helm@v1

      - name: Run chart
        uses: helm/chart-releaser-action@v1.4.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Upload chart
        env:
          GITHUG_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          REPO_NAME: "${{ github.event.repository.name }}"
          OWNER_REPO: "namnextx"
          CHART_PACKAGE_PATH: .cr-release-packages
          CHART_REGISTRY: ghcr.io
        run: |
          chmod +x ./push_chart.sh
          sh ./upload.sh ${CHART_PACKAGE_PATH}